# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - suttapak

networks:
  suttapak:
